# Generated by Django 6.0.3 on 2026-04-03 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='inventory.servicio'),
        ),
    ]
