# Generated by Django 6.0.3 on 2026-04-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicios',
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(blank=True, null=True, related_name='reservas', to='inventory.servicio'),
        ),
    ]
