# Generated by Django 6.0.3 on 2026-04-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_reserva_servicios_reserva_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atencion', to='inventory.reserva'),
        ),
    ]
