# Generated by Django 6.0.3 on 2026-04-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_atencion_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='reservas', to='inventory.servicio'),
        ),
    ]
