# Generated by Django 6.0.3 on 2026-04-16 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_reserva_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='inventory.empleado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='empleados',
            field=models.ManyToManyField(related_name='servicios', to='inventory.empleado'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha_turno'), name='unique_reserva_empleado_hora'),
        ),
    ]
