# Generated by Django 6.0.3 on 2026-04-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_empleado_reserva_empleado_servicio_empleados_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
