# Generated by Django 6.0.3 on 2026-04-16 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_empleado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='inventory.empleado'),
        ),
    ]
